filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "http://192.168.20.11:5601"

output.elasticsearch:
  hosts: ["192.168.20.11:9200"]
  protocol: "http"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
